#!/bin/bash
set -ex

cd /usr/local/src/process-exporter-master
ls -lah .

go get
make

mv process-exporter /usr/bin/process-exporter

systemctl daemon-reload
systemctl enable process-exporter
systemctl start process-exporter
