#!/bin/bash
set -ex

ls -lah /usr/local/


cd /usr/local/src/process-exporter-%VERSION%
go build -o process-exporter cmd/process-exporter/main.go
mv process-exporter /usr/bin/process-exporter

systemctl restart process-exporter.service
