#!/bin/bash
set -ex
sudo dpkg --list
sudo dpkg -L td-process-exporter
tree /usr/local/srs/

cd process-exporter-%VERSION%/usr/local/src/process-exporter-%VERSION%
go build -o process-exporter cmd/process-exporter/main.go
mv process-exporter /usr/bin/process-exporter

systemctl restart process-exporter.service
