name: build
env:
  version: '1.0.0'

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install golang
        run: |
          sudo add-apt-repository -y ppa:longsleep/golang-backports
          sudo apt-get update
          sudo apt-get install -y golang-go
      - name: Download sources
        run: |
          curl -L -o process-exporter.zip https://github.com/tada-team/process-exporter/archive/master.zip
          unzip process-exporter.zip
      - name: Prepare template
        run: |
          for arch in i386 amd64; do
            mkdir -p td-process-exporter_${{env.version}}_${arch}/usr/bin
            cp -rv DEBIAN.template td-process-exporter_${{env.version}}_${arch}/DEBIAN
            sed -i "s/%VERSION%/${{env.version}}/g" td-process-exporter_${{env.version}}_${arch}/DEBIAN/*
            sed -i "s/%ARCH%/${arch}/g" td-process-exporter_${{env.version}}_${arch}/DEBIAN/*
          done
      - name: Go build
        run: |
          set -ex
          mkdir -p dist
          for arch in i386 amd64; do
            cd process-exporter-master
            if [ "${arch}" == "i386" ]; then
              GOARCH=386 go build .
            else
              GOARCH=${arch} go build .
            fi
            cd ..
            mv -f process-exporter td-process-exporter_${{env.version}}_${arch}/usr/bin/process-exporter
            dpkg-deb --build td-process-exporter_${{env.version}}_${arch}
            mv td-process-exporter_${{env.version}}_${arch} dist
          done
          rm process-exporter-master.zip
          ls -lah dist
#      - name: Try install
#        working-directory: dist
#        run: |
#          sudo apt-get install -y golang-go
#          sudo dpkg -i td-process-exporter_${{env.version}}.deb
#      - name: Install SSH Client
#        uses: webfactory/ssh-agent@v0.4.1
#        with:
#          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
#      - name: Deploy
#        uses: JamesIves/github-pages-deploy-action@3.7.1
#        with:
#          REPOSITORY_NAME: tada-team/ppa
#          TARGET_FOLDER: td-process-exporter-dist
#          FOLDER: dist
#          SSH: true
#          BRANCH: main
