name: build
env:
  version: '1.0.3'

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Download sources
        run: |
          curl -L -o process-exporter.zip https://github.com/tada-team/process-exporter/archive/master.zip
          unzip process-exporter.zip
          rm process-exporter.zip
      - name: Prepare template
        run: |
          for arch in 'amd64' 'arm64'; do
            dest=td-process-exporter_${{env.version}}_${arch}
            mkdir -p ${dest}/usr/src ${dest}/usr/bin
            cp -rv DEBIAN.template ${dest}/debian
            cp -rv etc ${dest}/etc
            sed -i "s/%VERSION%/${{env.version}}/g" \
              ${dest}/debian/control \
              ${dest}/debian/changelog
            sed -i "s/%ARCH%/${arch}/g" \
              ${dest}/debian/control
            cp -r process-exporter-master ${dest}/usr/src/process-exporter
            ls -lah ${dest}
          done
          rm -rf process-exporter-master
      - name: Build requirements
        run: sudo apt-get install -y devscripts debhelper dh-systemd dh-golang binutils-aarch64-linux-gnu
      - name: Go build
        run: |
          set -ex
          mkdir -p dist
          for arch in 'amd64' 'arm64'; do
            cd td-process-exporter_${{env.version}}_${arch}
            env GOARCH=${arch} dpkg-buildpackage --no-sign --target-arch ${arch} --host-arch ${arch}
            mv ../td-process-exporter_${{env.version}}_${arch}.deb ../dist
            cd ..
          done
      - name: Try install
        working-directory: dist
        run: |
          set -ex
          sudo dpkg -i td-process-exporter_${{env.version}}_amd64.deb
          echo "/etc/process-exporter:" && ls -lah /etc/process-exporter
          sudo systemctl status process-exporter
      - name: Install SSH Client
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          REPOSITORY_NAME: tada-team/ppa
          TARGET_FOLDER: td-process-exporter-dist
          FOLDER: dist
          SSH: true
          BRANCH: main
