name: build
env:
  version: '0.7.2'
  debVersion: '+1'

on:
  push:
    branches: [ main, m1 ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Download sources
        run: |
          dest=td-process-exporter_${{env.version}}
          mkdir -p ${dest}/usr/local/src
          cd ${dest}/usr/local/src
          curl -L -o process-exporter-${{env.version}}.tar.gz https://github.com/tada-team/process-exporter/archive/v${{env.version}}.tar.gz
          tar zvxf process-exporter-${{env.version}}.tar.gz
          rm process-exporter-${{env.version}}.tar.gz
      - name: Prepare template
        run: |
            dest=td-process-exporter_${{env.version}}${{env.debVersion}}
            mkdir -p ${dest}/usr/src ${dest}/usr/bin
            cp -rv DEBIAN.template ${dest}/debian
            cp -rv etc ${dest}/etc
            sed -i "s/%VERSION%/${{env.version}}/g" \
              ${dest}/debian/control \
              ${dest}/debian/rules \
              ${dest}/debian/changelog
            sed -i "s/%DEB_VERSION%/${{env.debVersion}}/g" \
              ${dest}/debian/control \
              ${dest}/debian/changelog
      - name: Build requirements
        run: sudo apt-get install -y devscripts debhelper dh-systemd dh-golang tree
      - name: Build .deb
        run: |
          set -ex
          dest=td-process-exporter_${{env.version}}${{env.debVersion}}
          mkdir -p dist
          cd ${dest}
          dpkg-buildpackage --no-sign
          mv ../*.deb ../dist
#          cat ${dest}/DEBIAN/control
#          dpkg-deb --build ${dest}
#          mv ${dest}.deb dist
      - name: Try install
        working-directory: dist
        run: |
          dest=td-process-exporter_${{env.version}}${{env.debVersion}}
          sudo dpkg -i ${dest}.deb
          sudo systemctl status process-exporter
      - name: Install SSH Client
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          REPOSITORY_NAME: tada-team/ppa
          TARGET_FOLDER: td-process-exporter-dist
          FOLDER: dist
          SSH: true
          BRANCH: main
