name: build
env:
  version: '1.0.0'

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Prepare template
        run: |
          for arch in i386 amd64; do
            mkdir -p td-process-exporter_${{env.version}}_${arch}
            cp -rv DEBIAN.template td-process-exporter_${{env.version}}_${arch}/DEBIAN
            sed -i "s/%VERSION%/${{env.version}}/g" td-process-exporter_${{env.version}}_${arch}/DEBIAN/*
            sed -i "s/%ARCH%/${arch}/g" td-process-exporter_${{env.version}}_${arch}/DEBIAN/*
          done
#      - name: Download lib
#        run: |
#          mkdir -p td-process-exporter_${{env.version}}/usr/local/src
#          cd td-process-exporter_${{env.version}}/usr/local/src
#          curl -L -o process-exporter.zip https://github.com/tada-team/process-exporter/archive/master.zip
#          unzip process-exporter.zip
#          rm process-exporter.zip
#          mv process-exporter-master process-exporter
#      - name: Go build
#        run: |
#          GOARCH=i386 go build process-exporter
#          mv process-exporter usr/bin/process-exporter
#          rm process-exporter.zip
#      - name: Build .deb
#        run: |
#          dpkg-deb --build td-process-exporter_${{env.version}}
#          mkdir -p dist
#          mv td-process-exporter_${{env.version}}.deb dist
#          ls -lah dist
#      - name: Try install
#        working-directory: dist
#        run: |
#          sudo apt-get install -y golang-go
#          sudo dpkg -i td-process-exporter_${{env.version}}.deb
#      - name: Install SSH Client
#        uses: webfactory/ssh-agent@v0.4.1
#        with:
#          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
#      - name: Deploy
#        uses: JamesIves/github-pages-deploy-action@3.7.1
#        with:
#          REPOSITORY_NAME: tada-team/ppa
#          TARGET_FOLDER: td-process-exporter-dist
#          FOLDER: dist
#          SSH: true
#          BRANCH: main
