name: build
env:
  version: '1.0.0'

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Download sources
        run: |
          curl -L -o process-exporter.zip https://github.com/tada-team/process-exporter/archive/master.zip
          unzip process-exporter.zip
      - name: Prepare template
        run: |
          for arch in amd64; do
            mkdir -p \
              td-process-exporter_${{env.version}}_${arch}/usr/bin \
              td-process-exporter_${{env.version}}_${arch}/usr/src
            cp -rv etc td-process-exporter_${{env.version}}_${arch}/etc
            cp -rv DEBIAN.template td-process-exporter_${{env.version}}_${arch}/debian
            sed -i "s/%VERSION%/${{env.version}}/g" td-process-exporter_${{env.version}}_${arch}/debian/*
            sed -i "s/%ARCH%/${arch}/g" td-process-exporter_${{env.version}}_${arch}/debian/*
            cp -r process-exporter-master td-process-exporter_${{env.version}}_${arch}/usr/src/process-exporter
            ls -lah td-process-exporter_${{env.version}}_${arch}
          done
      - name: Build requirements
        run: sudo apt-get install -y devscripts debhelper dh-systemd dh-golang
      - name: Go build
        run: |
          set -ex
          mkdir -p dist
          for arch in amd64; do
            cd td-process-exporter_${{env.version}}_${arch}
            dpkg-buildpackage --no-sign --target-arch ${arch}
            mv ../td-process-exporter_${{env.version}}_${arch}.deb ../dist
            cd ..
          done
          ls -lah dist
      - name: Try install
        working-directory: dist
        run: |
          sudo dpkg -i td-process-exporter_${{env.version}}_amd64.deb
          service status process-exporter
      - name: Install SSH Client
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          REPOSITORY_NAME: tada-team/ppa
          TARGET_FOLDER: td-process-exporter-dist
          FOLDER: dist
          SSH: true
          BRANCH: main
